export const marketDataSchema = `
CREATE TABLE IF NOT EXISTS base_market_data (
    record_id INTEGER PRIMARY KEY AUTOINCREMENT,
    id TEXT,
    symbol TEXT,
    name TEXT,
    image TEXT,
    current_price REAL,
    market_cap REAL,
    market_cap_rank INTEGER,
    fully_diluted_valuation REAL,
    total_volume REAL,
    high_24h REAL,
    low_24h REAL,
    price_change_24h REAL,
    price_change_percentage_24h REAL,
    market_cap_change_24h REAL,
    market_cap_change_percentage_24h REAL,
    circulating_supply REAL,
    total_supply REAL,
    max_supply REAL,
    ath REAL,
    ath_change_percentage REAL,
    ath_date TEXT,
    atl REAL,
    atl_change_percentage REAL,
    atl_date TEXT,
    last_updated TEXT,
    price_change_percentage_1h_in_currency REAL,
    price_change_percentage_24h_in_currency REAL,
    price_change_percentage_7d_in_currency REAL,
    price_change_percentage_14d_in_currency REAL,
    price_change_percentage_30d_in_currency REAL,
    price_change_percentage_200d_in_currency REAL,
    category TEXT,
    timestamp INTEGER,
    UNIQUE(id, timestamp, category)
)`;

export { tokenInfoSchema } from "./tokenInfoSchema";
